### ISSUE TITLE
Please add the error registers to the JSON specification

### ISSUE THREAD

**Issue by glados-verma** [labjack/ljm_constants#18]
The error registers are documented on the [Labjack website](https://labjack.com/support/software/api/modbus/protocol-details):

> Any time there is an error, further information is available by reading from a group of 4 registers that start at 55000.  There are 8 of these groups with starting addresses from 55000 to 55028.  For example, the first group is:
> 
> 55000: LabJack Error Code #0
> 55001: Error Frame #0
> 55002: Modbus Error #0
> 55003: Transaction ID #0
> 
> The standard Modbus functions (3/4/6/16) only use the first error information group shown above.

Please document, at minimum, register 55000.

**Comment by sjarman28** [comment]
We will add documentation for the error register(s). We have not decided how we want to do this yet, but I will follow up when it is done. Please note that if you are using the LJM library you should not typically use these error registers. LJM will automatically handle low level errors and propagate them as LJM errors.

**Comment by glados-verma** [comment]
Thank you - I'm using the Modbus interface, and have to read the registers directly.

**Comment by code-monet** [comment]
Excellent, thanks!

**Comment by glados-verma** [comment]
Appreciate it!
