### ISSUE TITLE
Can STREAM_DATATYPE be added to ljm_constants?

### ISSUE THREAD

**Issue by glados-verma** [labjack/ljm_constants#19]
The doc for low level stream [simply says](https://labjack.com/support/datasheets/t-series/communication/stream-mode/low-level-streaming) that the register is not available in the JSON file. I'm curious if this is intentional, or if you're open to adding the register to the JSON?

**Comment by sjarman28** [comment]
We have intentionally left this register undocumented. We were considering support for different binary bit-ness options when using stream mode, but we ended up only supporting 16-bit binary. As such, the STREAM_DATATYPE register does not have any use outside of ensuring it is 0 for low-level stream, and we want to leave it as a hidden/unimplemented feature in regards to LJM access.

**Comment by glados-verma** [comment]
Is it still required to be written 0 for low level configuration? From the docs: "Additionally, address 4018 (STREAM_DATATYPE) must be written with the value 0". It's a little weird to have to hard-code the register address - perhaps future firmware revisions could skip requiring this register being written?

**Comment by sjarman28** [comment]
The current firmware (1.0292 for T7 and 1.0027 for T4 and up) does not require you to write to STREAM_DATATYPE , the default value is 0. Just looking quickly at the project history/changelog, it is not clear if or when older firmware did not use 0 as the default, so the low level docs describe the register to be safe. We are going to clean this up in documentation.
